In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
x = torch.rand(5, 3)

print(x)
torch.zeros(1).cuda()

tensor([[0.3315, 0.4192, 0.5727],
        [0.8478, 0.0692, 0.8708],
        [0.4752, 0.5004, 0.3081],
        [0.1878, 0.7787, 0.5506],
        [0.9546, 0.6391, 0.8657]])


tensor([0.], device='cuda:0')

In [2]:
vector=torch.Tensor([[1,2,3,0],[4,5,6,2],[7,8,9,5]])
vector.ndim

2

In [3]:
vector.shape

torch.Size([3, 4])

In [4]:
vector[0][2]

tensor(3.)

In [5]:
random_tensor=torch.rand(size=(224,224,3))
random_tensor.ndim,random_tensor.dtype

(3, torch.float32)

In [6]:
torch.zeros(3,3)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(3,3).dtype

torch.float32

In [8]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
torch.cuda

<module 'torch.cuda' from 'c:\\Users\\merug\\anaconda3\\envs\\cuda\\Lib\\site-packages\\torch\\cuda\\__init__.py'>

In [11]:
zero_to_ten = torch.arange(start=0, end=10, step=1)

In [12]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

<ul>
<li>tensor are not right datatype </li>
<li> tensor are not right shape</li>
 <li>tensor are not on the right device</li> </ul>

In [15]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device='cuda', # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cuda', index=0))

In [18]:
float_32_tensor.device

device(type='cuda', index=0)

### matrix multiplication
1) element wise multiply
2) matrix multiplication(dot product)
* matmul is more optimized than for loop
* a.T=transpose
* matmul(t1,t2) alias mm
* default dtype=float32

### max,min,mean,sum,aggregation functions
* mean only for float type basic concepts(t.type(torch.float32).mean()) or torch.mean(t.type(torch.float32))
* torch.argmin()=> returns the minimum position of the list

In [27]:
x=torch.rand(size=(3,4))

In [63]:
x=torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
x[x.argmin()]
x[x.argmax()]


tensor(9)

### tensor squeezing,stacking,unsquezzing